### ISSUE TITLE
LaserTools window too tall 

### ISSUE THREAD

**Issue by oilytin** [ChrisWag91/Inkscape-Lasertools-Plugin#18]
Hi the popup is too tall for my screen (1080p) i am unable to see or click the apply button.
Windows 10, Inkscape 0.92
Thanks Anthony
![image](https://user-images.githubusercontent.com/64922090/97292361-10489600-1843-11eb-896b-28577f681d8e.png)

**Comment by oilytin** [comment]
not sure if this tab is the cause of the problem
![image](https://user-images.githubusercontent.com/64922090/97297825-7389f680-184a-11eb-848a-e232bc9352d0.png)

**Comment by oilytin** [comment]
upgraded to 1.0 and the problem is gone

**Comment by ChrisWag91** [comment]
Hi,
I tried to reproduce the issue in windows and linux in v0.92 without any luck.
It displays as intended on my system:

![image](https://user-images.githubusercontent.com/33778554/97410264-2320a080-18ff-11eb-9d3d-21746e392cce.png)

But the issue seems to pop up in some installations.
It is almost certainly caused by the debug text in your screenshot. 
According to the lasertools.inx file there should not be any text in front of the textboxes:
![image](https://user-images.githubusercontent.com/33778554/97411050-0e90d800-1900-11eb-805c-a490efa88f82.png)

Adding a space or a dash in there might fix the problem.
If someone has a chance to test that, please let me know if it solved the problem.

**Comment by oilytin** [comment]
Before i moved to the 1.0 version i did try adding something in those quotes but it didnt seem to make any difference with the same output as above.

**Comment by oilytin** [comment]
I also tried the 32 and 64 bit .92 releases but that didn't make any difference either.

**Comment by Lannert** [comment]
Hi,
i also had the problem with the tall windows (Inkscape 0.92, MacOSX). I added the spaces as recommended and everything is fine. 
Thank you very much for this plugin! It works very good and i enjoy it.

**Comment by ChrisWag91** [comment]
Thanks for the Feedback. 
I'll add the spaces in master.
